/* CS = Client to Server*/
const CS_SOCKET_MESSAGES = {
	CS_SOCKET_CONNECTED: 'CS_SOCKET_CONNECTED',
	CS_SOCKET_DICSONNECTED: 'CS_SOCKET_DICSONNECTED',
};

Object.freeze(CS_SOCKET_MESSAGES);

module.exports = CS_SOCKET_MESSAGES;
