/* SC = Server to Client */
const SC_SOCKET_MESSAGES = {
	SC_SOCKET_CONNECTED: 'SC_SOCKET_CONNECTED',
	SC_SOCKET_DISCONNECTED: 'SC_SOCKET_DISCONNECTED',
	SC_UPDATE_LOBBY_ONLINE_LIST: 'SC_UPDATE_LOBBY_ONLINE_LIST',
};

Object.freeze(SC_SOCKET_MESSAGES);

module.exports = SC_SOCKET_MESSAGES;
